### ISSUE TITLE
Error dumping logs

### ISSUE THREAD

**Issue by n0valis** [Jwink3101/syncrclone#15] opened 2021-12-10 14:12 UTC
I get this error from syncrclone but I dont know how to address it. 

`ERROR. Dumping logs (with debug) to '/tmp/tmpvjagqmzw/log.txt'
2021-12-10 15:00:01: ERROR: Compressed file ended before the end-of-stream marker was reached

ERROR. Dumping logs (with debug) to '/tmp/tmpp2tz79y4/log.txt'
2021-12-10 15:00:02: ERROR: Compressed file ended before the end-of-stream marker was reached

ERROR. Dumping logs (with debug) to '/tmp/tmpcvyzt4_t/log.txt'
2021-12-10 15:00:02: ERROR: Compressed file ended before the end-of-stream marker was reached

ERROR. Dumping logs (with debug) to '/tmp/tmptrf8rniv/log.txt'
2021-12-10 15:00:03: ERROR: Compressed file ended before the end-of-stream marker was reached`

If I look into log.txt everything looks fine.

**Comment by Jwink3101** [comment] 2021-12-10 15:02
That's odd. Can you run with --debug and then post the _full_ output. (And/or the full output of log.txt which should be the same). 

You only posted the tiny snippet saying there was an error and not enough to go on otherwise. 

What remotes are you using? Are you running the latest rclone?

**Comment by n0valis** [comment] 2021-12-10 22:29
This is the output for google. But I am using 3 others (non-google) where the same error occurs.

`2021-12-10 23:18:32: DEBUG: argv: ['/usr/local/share/syncrclone/config-google.py']
2021-12-10 23:18:32: DEBUG: CLI config: Namespace(configpath='/usr/local/share/syncrclone/config-google.py', break_lock=None, debug=False, dry_run=False, interactive=False, new=False, no_backup=False, override=[], reset_state=False)
2021-12-10 23:18:32: DEBUG: Localmode: False
2021-12-10 23:18:32: syncrclone (20211015.0.BETA)
2021-12-10 23:18:32: config path: '/usr/local/share/syncrclone/config-google.py'
2021-12-10 23:18:32: A: '/mnt/Backup/Cloud/Google'
2021-12-10 23:18:32: B: 'Google:'
2021-12-10 23:18:32: DEBUG: config: Config(remoteA='/mnt/Backup/Cloud/Google', remoteB='Google:', name='q8Z9C', rclone_exe='/usr/bin/rclone', filter_flags=[], rclone_flags=['--config', '/mnt/homes/xy/.config/rclone/rclone.conf', '--drive-skip-gdocs', '-vv'], rclone_env={}, rclone_flagsA=[], rclone_flagsB=[], compare='mtime', dt=1.1, conflict_mode='newer', tag_conflict=False, reuse_hashesA=False, reuse_hashesB=False, always_get_mtime=True, backup=False, sync_backups=False, hash_fail_fallback=None, set_lock=False, action_threads=1, cleanup_empty_dirsA=None, cleanup_empty_dirsB=None, avoid_relist=False, renamesA=None, renamesB=None, log_dest='.syncrclone/logs', local_log_dest='', pre_sync_shell='', post_sync_shell='', stop_on_shell_error=False, configpath='/usr/local/share/syncrclone/config-google.py', break_lock=None, debug=False, dry_run=False, interactive=False, new=False, override=[], reset_state=False)
2021-12-10 23:18:32: rclone version:
2021-12-10 23:18:32: DEBUG: rclone:call ['/usr/bin/rclone', '--version']
2021-12-10 23:18:32: DEBUG: rclone: env {'RCLONE_ASK_PASSWORD': 'false'}
2021-12-10 23:18:32: rclone: rclone v1.56.2
2021-12-10 23:18:32: rclone: - os/version: debian 11.1 (64 bit)
2021-12-10 23:18:32: rclone: - os/kernel: 5.14.0-0.bpo.2-amd64 (x86_64)
2021-12-10 23:18:32: rclone: - os/type: linux
2021-12-10 23:18:32: rclone: - os/arch: amd64
2021-12-10 23:18:32: rclone: - go/version: go1.16.8
2021-12-10 23:18:32: rclone: - go/linking: static
2021-12-10 23:18:32: rclone: - go/tags: none
2021-12-10 23:18:32: 
2021-12-10 23:18:32: Refreshing file list on A '/mnt/Backup/Cloud/Google'
2021-12-10 23:18:32: DEBUG: rclone:call ['/usr/bin/rclone', 'lsjson', '--filter', '+ /.syncrclone/A-q8Z9C_fl.json.xz', '--filter', '+ /.syncrclone/LOCK/*', '--filter', '- /.syncrclone/**', '--config', '/mnt/homes/xy/.config/rclone/rclone.conf', '--drive-skip-gdocs', '-vv', '-R', '--no-mimetype', '--files-only', '/mnt/Backup/Cloud/Google']
2021-12-10 23:18:32: DEBUG: rclone: env {'RCLONE_ASK_PASSWORD': 'false'}
2021-12-10 23:18:32:  rclone stderr: 2021/12/10 23:18:32 DEBUG : Setting --ask-password "false" from environment variable RCLONE_ASK_PASSWORD="false"
2021/12/10 23:18:32 DEBUG : rclone: Version "v1.56.2" starting with parameters ["/usr/bin/rclone" "lsjson" "--filter" "+ /.syncrclone/A-q8Z9C_fl.json.xz" "--filter" "+ /.syncrclone/LOCK/*" "--filter" "- /.syncrclone/**" "--config" "/mnt/homes/xy/.config/rclone/rclone.conf" "--drive-skip-gdocs" "-vv" "-R" "--no-mimetype" "--files-only" "/mnt/Backup/Cloud/Google"]
2021/12/10 23:18:32 DEBUG : Creating backend with remote "/mnt/Backup/Cloud/Google"
2021/12/10 23:18:32 DEBUG : Using config file from "/mnt/homes/xy/.config/rclone/rclone.conf"
2021/12/10 23:18:32 DEBUG : .syncrclone/logs: Excluded
2021/12/10 23:18:32 DEBUG : 2 go routines active

2021-12-10 23:18:32: DEBUG: A: Read 1327
2021-12-10 23:18:32: DEBUG: A: Read 1327
2021-12-10 23:18:32: DEBUG: Pulling prev list on A
2021-12-10 23:18:32: DEBUG: rclone:call ['/usr/bin/rclone', '--config', '/mnt/homes/xy/.config/rclone/rclone.conf', '--drive-skip-gdocs', '-vv', 'copyto', '/mnt/Backup/Cloud/Google/.syncrclone/A-q8Z9C_fl.json.xz', '/tmp/tmpc818cp_y/A_prev']
2021-12-10 23:18:32: DEBUG: rclone: env {'RCLONE_ASK_PASSWORD': 'false'}
2021-12-10 23:18:32:  rclone stderr: 2021/12/10 23:18:32 DEBUG : Setting --ask-password "false" from environment variable RCLONE_ASK_PASSWORD="false"
2021/12/10 23:18:32 DEBUG : rclone: Version "v1.56.2" starting with parameters ["/usr/bin/rclone" "--config" "/mnt/homes/xy/.config/rclone/rclone.conf" "--drive-skip-gdocs" "-vv" "copyto" "/mnt/Backup/Cloud/Google/.syncrclone/A-q8Z9C_fl.json.xz" "/tmp/tmpc818cp_y/A_prev"]
2021/12/10 23:18:32 DEBUG : Creating backend with remote "/mnt/Backup/Cloud/Google/.syncrclone/A-q8Z9C_fl.json.xz"
2021/12/10 23:18:32 DEBUG : Using config file from "/mnt/homes/xy/.config/rclone/rclone.conf"
2021/12/10 23:18:32 DEBUG : fs cache: adding new entry for parent of "/mnt/Backup/Cloud/Google/.syncrclone/A-q8Z9C_fl.json.xz", "/mnt/Backup/Cloud/Google/.syncrclone"
2021/12/10 23:18:32 DEBUG : Creating backend with remote "/tmp/tmpc818cp_y/"
2021/12/10 23:18:32 DEBUG : A-q8Z9C_fl.json.xz: Need to transfer - File not found at Destination
2021/12/10 23:18:32 DEBUG : A-q8Z9C_fl.json.xz: md5 = d41d8cd98f00b204e9800998ecf8427e OK
2021/12/10 23:18:32 INFO  : A-q8Z9C_fl.json.xz: Copied (new) to: A_prev
2021/12/10 23:18:32 INFO  : 
Transferred:   	          0 / 0 Byte, -, 0 Byte/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.0s

2021/12/10 23:18:32 DEBUG : 4 go routines active`

**Comment by Jwink3101** [comment] 2021-12-10 23:39
A few thoughts:

* Do **not** have `-vv` in the `rclone_flags`. Syncrclone expects certain responses and debug levels. That may be the main issue anyway. I honestly don't know.
* Is `/mnt/Backup/Cloud/Google` an rclone mount?

However what is bothering me is:

> ```
> ERROR: Compressed file ended before the end-of-stream marker was reached
> ```

and 

> ```
> Transferred: 0 / 0 Byte, -, 0 Byte/s, ETA -
> Transferred: 1 / 1, 100%
> Elapsed time: 0.0s
> ```

Based on https://stackoverflow.com/a/64235617/3633154 it sounds like it may be an issue with Google? Or somehow the previous list failed.

If you run with `--reset-state`, does it work? 

> But I have set them up all the same and they were working until Dec 2nd.

Nothing on the syncrclone side has changed. You're running the version from October. It sounds like a transfer of the previous state failed somehow. Do you happen to have the logs from the last "successful" run? I wonder if there was an error there. Either way, `--reset-state` should fix that. (

**Comment by n0valis** [comment] 2021-12-11 12:08
I thought you meant I should run rclone with debug level, that's why I added -vv to the flags. 
So what you see above is a result of -vv. 
Without it the file would just end after 
>Refreshing file list on A '/mnt/Backup/Cloud/Google'

and would have no DEBUG output obviously. 

But now I get it, you mean syncrclone with --debug. 
Here is the output:

ERROR. Dumping logs (with debug) to '/tmp/tmp2p5yib3i/log.txt'
Traceback (most recent call last):
  File "/opt/miniconda/bin/syncrclone", line 8, in <module>
    sys.exit(cli())
  File "/opt/miniconda/lib/python3.9/site-packages/syncrclone/cli.py", line 259, in cli
    r = SyncRClone(config,break_lock=config.break_lock)
  File "/opt/miniconda/lib/python3.9/site-packages/syncrclone/main.py", line 43, in __init__
    self.currA,self.prevA = self.rclone.file_list(remote='A')
  File "/opt/miniconda/lib/python3.9/site-packages/syncrclone/rclone.py", line 245, in file_list
    prev_list = self.pull_prev_list(remote=AB)
  File "/opt/miniconda/lib/python3.9/site-packages/syncrclone/rclone.py", line 169, in pull_prev_list
    return json.load(file)
  File "/opt/miniconda/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/miniconda/lib/python3.9/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/opt/miniconda/lib/python3.9/_compression.py", line 99, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

As I mentioned, one syncjob still works fine. It is also a Google account. The other four include dropbox, onedrive, google.

**Comment by n0valis** [comment] 2021-12-11 12:49
And yes, --reset-state fixed the issue. 
Could you please explain? 
I know you can't fully know what's going on on my computer but at least what are your thoughts? 

However, thank you very much for your time and effort.

**Comment by Jwink3101** [comment] 2021-12-11 14:57
> `--reset-state` fixed the issue.

Great!

> Could you please explain?

This is just a guess, though the `--debug` you posted makes me more sure of the fix and less sure of the cause.

syncrclone keeps the previous state of the files. It needs this because otherwise you can't propagate deleted files and you won't know about conflicted modification times.

What seems to have happened is the previous state file, `A-q8Z9C_fl.json.xz` did not get uploaded properly. That is why I asked if you had the log for the last "correct" upload. I suspect rclone threw an error (since it is very good about detecting if things get uploaded wrong) but it was at the end and you didn't notice since everything else worked great.

When you run with `--reset-state`, it does not try to get the previous state. This is not an ideal mode though since it will (a) not propagate deletes and (b) all modified files will look like a conflict (since it won't be able to know that one was not modified and the other was). 

BTW, if you're interested, in the latest version, there is a few things you could do to speed this up.

* Set `avoid_relist = True` (see [config](https://github.com/Jwink3101/syncrclone/blob/a5be61c4260c7555e3548a7663db7ef1aeb18eb0/syncrclone/config_example.py#L176)). If your original config was created with an older one, you have to copy it in (see [tips](https://github.com/Jwink3101/syncrclone/blob/master/docs/config_tips.md#updating-configs)). This is experimental but has been working very well for me. It saves the additional relist time with a few minor caveats
* Add `--fast-list` to your `rclone_flags`. I don't use Google Drive. In fact, I've never even tested it there. But it does support `listR` so it'll be faster to list.

Anyway, glad it is all working. Feel free to ask any followups but I am going to close the issue.

**Closed by Jwink3101** 2021-12-11 14:57 UTC
